"""Added user type

Revision ID: fbe3deeac7a3
Revises: 2e264255866c
Create Date: 2023-12-31 14:07:34.248165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe3deeac7a3'
down_revision: Union[str, None] = '2e264255866c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.Enum('ADMIN', 'EDITOR', 'MANAGER', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
